# Generated by Django 2.1.3 on 2019-05-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190517_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='residence',
            field=models.CharField(choices=[('1st', 'First'), ('2nd', 'Second'), ('3rd', 'Third'), ('4th', 'Fourth'), ('NGH', 'NGH'), ('Non_hosteler', 'Non_hosteler'), ('Teacher_quarter', 'Teacher_quarter')], default='1st', max_length=20),
        ),
    ]
