# Generated by Django 2.1.3 on 2019-05-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('NV', 'NV'), ('V', 'V'), ('IP', 'IP'), ('C', 'C')], max_length=2),
        ),
    ]
