# Generated by Django 2.1.3 on 2019-05-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chp', '0002_auto_20190517_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='Recepient',
            new_name='recepient',
        ),
        migrations.AlterField(
            model_name='complain',
            name='complain_subject',
            field=models.CharField(help_text='Enter the complain subject', max_length=100),
        ),
    ]
