# Generated by Django 2.1.3 on 2019-05-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chp', '0003_auto_20190517_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complain_description',
            field=models.TextField(max_length=2000),
        ),
    ]
